### ISSUE TITLE
BAD REQUEST(400) - error parsing labels: parse error at line {0}, col {1}: invalid char escape

### ISSUE THREAD

**Issue by pcbl** [JosephWoodward/Serilog-Sinks-Loki#12]
Hi Folks,

I added the Loki Serilog Sink on my Project, but I noticed(when I enable Visual Studio to Stop on all Exceptions), that I am getting a BadRequest response such as the one bellow:

(Note that my Loki is running on port 11187)....
**REQUEST BODY:**
`
POST http://localhost:11187/api/prom/push HTTP/1.1
Host: localhost:11187
Content-Type: application/json
Content-Length: 782

{"streams":[{"labels":"{level=\"info\",app=\"demoapp\",environment=\"production\",CallerAssembly=\"Lalalal.Fab.Framework.WebApi.Service, Version=6.1.1.0, Culture=neutral, PublicKeyToken=null\",CallerClassName=\"Lalalal.Fab.Framework.WebApi.Service.Extensions.XaLogExtensions\",CallerMemberName=\"InitializeXaLog\",CallerFileName=\"C:\\Lalalal\\LalalalFab_Framework\\WebApi.Service\\Source\\Extensions\\XaLogExtensions.cs\",CallerFileLineNumber=\"88\",Application=\"ILoggerWebAPI\",ApplicationVersion=\"{ Major: 1, Minor: 0, Patch: 0 }\",CorrelationId=\"null\",ProcessId=\"1308\",ThreadId=\"1\",MachineName=\"DEPC009734\"}","entries":[{"ts":"2020-05-18T14:50:44.4335725+02:00","line":"Logging initialized with Threshold: 'Debug'. Log setttings were read by 'APP_SETTING_JSON'.\r\n"}]}]}
`

**RESPONSE BODY:**
`
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Mon, 18 May 2020 12:50:44 GMT
Content-Length: 74

error parsing labels: parse error at line 1, col 293: invalid char escape
`

**Visual Studio $exception:**
`
$exception.ToString() = Serilog.Debugging.LoggingFailedException: Received failed result BadRequest when posting events to http://localhost:11187/api/prom/push
   at Serilog.Sinks.Http.Private.Sinks.HttpSink.EmitBatchAsync(IEnumerable`1 logEvents)
`

What I think is curious, is that the Log entry ends up landing properly on Loki.... So I am not completely sure what is going on... Does anyone else faced this issue? What am i missing?

BR
Pedro

**Comment by JosephWoodward** [comment]
Interesting, are you by any chance able to provide a reproduction of this?

**Comment by pcbl** [comment]
Hi Joseph,

Sure. Just clone this repo:
https://github.com/pcbl/TestSerilogLokiSink

Before you run it, check the "Common Language Runtime Exceptions" on Visual Studio on Exception Windows(CTRL+ALT+E). This will throw an exception on VS like:
`Serilog.Debugging.LoggingFailedException: 'Received failed result BadRequest when posting events to http://localhost:11187/api/prom/push'`

If you have a look on Fidler (https://www.telerik.com/download/fiddler):

**Request body:**
POST http://localhost:11187/api/prom/push HTTP/1.1
Host: localhost:11187
Content-Type: application/json
Content-Length: 875

{"streams":[{"labels":"{level=\"info\",address=\"http://localhost:5000\",SourceContext=\"Microsoft.Hosting.Lifetime\"}","entries":[{"ts":"2020-05-19T10:38:48.8645389+02:00","line":"Now listening on: \"http://localhost:5000\"\r\n"}]},{"labels":"{level=\"info\",SourceContext=\"Microsoft.Hosting.Lifetime\"}","entries":[{"ts":"2020-05-19T10:38:48.8651357+02:00","line":"Application started. Press Ctrl+C to shut down.\r\n"}]},{"labels":"{level=\"info\",envName=\"Development\",SourceContext=\"Microsoft.Hosting.Lifetime\"}","entries":[{"ts":"2020-05-19T10:38:48.8651488+02:00","line":"Hosting environment: \"Development\"\r\n"}]},{"labels":"{level=\"info\",contentRoot=\"C:\\github\\TestSerilogLokiSink\",SourceContext=\"Microsoft.Hosting.Lifetime\"}","entries":[{"ts":"2020-05-19T10:38:48.8651529+02:00","line":"Content root path: \"C:\\github\\TestSerilogLokiSink\"\r\n"}]}]}


**Response Body:**
_HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Tue, 19 May 2020 08:38:48 GMT
Content-Length: 73_

error parsing labels: parse error at line 1, col 27: invalid char escape

To me it sounds that the Labels which are creating trouble...

**Comment by JosephWoodward** [comment]
Great, thanks for this.

**Comment by mishamyte** [comment]
@JosephWoodward , also, I want to notice that the API used by your sink is deprecated (https://github.com/grafana/loki/blob/v1.4.1/docs/api.md#post-apiprompush)

Now there are 5 Serilog Sinks, related to Loki. And 2 of them use deprecated Loki API. I think it would be good it your sink (which is the "father" of all Loki sinks) could use actual API
(Detailed comparison of functionality of existing sinks [I made here](https://github.com/mishamyte/serilog-sinks-grafana-loki/wiki/Comparison-with-another-Loki-sinks)

**Comment by steveadoo32** [comment]
FYI - not an issue with v1.0.0 of the nuget package. Using that for now seems to work.

**Comment by m-mccormick** [comment]
I have run into a similar issue. Loki appears to be finicky about what characters can be included in the name and content of labels, especially in the deprecated [POST /api/prom/push](https://github.com/grafana/loki/blob/master/docs/api.md#post-apiprompush) which Serilog-Sinks-Loki uses. The newer [POST /loki/api/v1/push](https://github.com/grafana/loki/blob/master/docs/api.md#post-lokiapiv1push) appears to be less finicky, especially outside the ASCII character space. Further, the `/api/prom/push` doesn't like nested quotes such as in `"line":"Now listening on: "http://localhost:5000"\r\n"` in your examples. Also, this is difficult to debug since serilog batch requests obscure the source of the issue, and it took me a long time to figure out what was causing bad requests. I started writing a dot net client library for the entire Loki API with character filtering mechanism to address this limitation, including integration tests, but I haven't had time to allocate recently.

**Comment by steveadoo32** [comment]
It looks like this commit introduced the issue:
https://github.com/JosephWoodward/Serilog-Sinks-Loki/commit/44c3f74e7f86821e700daf5af9f5a2f660ae3363#diff-ef54f04cd293a84a06ce9c70846f1bc5R65

StringBuilder on windows uses \r\n for newlines, which Loki doesn't seem to like. We will be submitting a PR soon with a fix that is working for us. It doesn't seem like Loki likes backslashes in labels either - we are just flipping them to forward slashes at this time.
