### ISSUE TITLE
Too many labels?

### ISSUE THREAD

**Issue by bradacina** [JosephWoodward/Serilog-Sinks-Loki#14]
Hi Joseph,

First and foremost: Thank you for this package! It certainly saved me a lot of time.

I've added it as a package to an asp.net core application and it's successfully sending logs to a loki instance that we run. The downside is that there are a lot of labels being sent with each log line. This is due to the call to `.Enrich.FromLogContext()` that we add to the Serilog configuration. This context information is great to have but not always necessary as a stream in loki. Reading through the loki design documents I came across this little gem: https://grafana.com/blog/2020/04/21/how-labels-in-loki-can-make-log-queries-faster-and-easier/ which states that each label:value combination constitutes a stream and that having too many streams will kill performance.

Would you accept PRs that add a configuration option to allow the user to specify a list of log event properties (if they are present) that should be used as labels and all other properties from the context be appended to the log message. Or better yet, two lists of properties, one to be used as labels, one to be appended to the log message and all other properties from the log context be discarded?

Thanks ,
Bo

**Comment by JosephWoodward** [comment]
@bradacina Yes, that sounds like something this library should have. I'd be interested to see what the PR looks like.

**Comment by bradacina** [comment]
@JosephWoodward here's what I have in mind: https://github.com/JosephWoodward/Serilog-Sinks-Loki/pull/15

I haven't looked at your unit tests or benchmarks yet.

**Comment by castrinho** [comment]
@JosephWoodward I'm also very interested in this feature. Is there any way I can help in order to this feature to be available ASAP?
I've also seen that the library is using a deprecated endpoint of the loki api, are there any plans to start using the new recommended endpoint?

**Comment by JosephWoodward** [comment]
> @JosephWoodward here's what I have in mind: https://github.com/JosephWoodward/Serilog-Sinks-Loki/pull/15
> 
> 
> 
> I haven't looked at the unit tests or benchmarks yet.

Thanks for your pull request, I’ll take a look at it this evening. It’d be good to get this one deployed as soon as possible.

**Comment by JosephWoodward** [comment]
> @JosephWoodward I'm also very interested in this feature. Is there any way I can help in order to this feature to be available ASAP?
> 
> I've also seen that the library is using a deprecated endpoint of the loki api, are there any plans to start using the new recommended endpoint? 

Yeah, I’d like to migrate to the new endpoint but I’m also conscious of breaking changes so may introduce some flag around which endpoint to use (so those on an older version of Loki won’t experience breaking changes).

**Comment by bradacina** [comment]
Hi @JosephWoodward . Is there anything that needs doing (or anything you need help with) to get this issue moving forward?

**Comment by JosephWoodward** [comment]
@bradacina No, I don't think so. I've pulled it down locally and have been going through it. It seems some of the tests are failing so I'm trying to understand why.

**Comment by bradacina** [comment]
Since I have not looked at the unit tests at all, I'll do the same on my end and see if something jumps out at me.

**Comment by steveadoo32** [comment]
I also ran into this issue. I ended up extending the LogLabelProvider with a list of property names to ignore.

I also noticed that the LokiBatchFormatter was added a new loki content stream per log event, rather than aggregating all the log events by labels and adding entries for each aggregate. 

After making those two changes, my loki chunks went from over a million from a week of runtime down to about ~4k.

My Format method in LokiBatchFormatter ended up like this:
```

        public void Format(IEnumerable<LogEvent> logEvents, ITextFormatter formatter, TextWriter output)
        {
            if (logEvents == null)
                throw new ArgumentNullException(nameof(logEvents));
            if (output == null)
                throw new ArgumentNullException(nameof(output));

            List<LogEvent> logs = logEvents.ToList();
            if (!logs.Any())
                return;

            var streamsDictionary = new Dictionary<string, LokiContentStream>();
            foreach (LogEvent logEvent in logs)
            {
                var labels = new List<LokiLabel>();

                labels.Add(new LokiLabel("level", GetLevel(logEvent.Level)));
                foreach (LokiLabel globalLabel in _globalLabels)
                {
                    labels.Add(new LokiLabel(globalLabel.Key, globalLabel.Value));
                }

                foreach (KeyValuePair<string, LogEventPropertyValue> property in logEvent.Properties)
                {
                    // Some enrichers pass strings with quotes surrounding the values inside the string,
                    // which results in redundant quotes after serialization and a "bad request" response.
                    // To avoid this, remove all quotes from the value.
                    // We also remove any \r\n newlines and replace with \n new lines to prevent "bad request" responses
                    // We also remove backslashes and replace with forward slashes, Loki doesn't like those either
                    if (IgnoreLogEventProperty(property.Key))
                    {
                        continue;
                    }
                    labels.Add(new LokiLabel(property.Key, property.Value.ToString().Replace("\"", "").Replace("\r\n", "\n").Replace("\\", "/")));
                }

                var localTime = logEvent.Timestamp.LocalDateTime;
                var localTimeAndOffset = new DateTimeOffset(localTime, TimeZoneInfo.Local.GetUtcOffset(localTime));
                var time = localTimeAndOffset.ToString("o");

                var sb = new StringBuilder();
                sb.AppendLine(logEvent.RenderMessage());
                if (logEvent.Exception != null)
                {
                    var e = logEvent.Exception;
                    while (e != null)
                    {
                        sb.AppendLine(e.Message);
                        sb.AppendLine(e.StackTrace);
                        e = e.InnerException;
                    }
                }

                // Order the labels so they always get the same chunk in loki
                labels = labels.OrderBy(l => l.Key).ToList();
                string key = string.Join(",", labels.Select(l => $"{l.Key}={l.Value}"));
                if (!streamsDictionary.TryGetValue(key, out var stream))
                {
                    streamsDictionary.Add(key, stream = new LokiContentStream
                    {
                        Labels = labels
                    });
                }

                // Loki doesn't like \r\n for new line, and we can't guarantee the message doesn't have any
                // in it, so we replace \r\n with \n on the final message
                stream.Entries.Add(new LokiEntry(time, sb.ToString().Replace("\\", "/").Replace("\r\n", "\n")));
            }

            var content = new LokiContent
            {
                Streams = streamsDictionary.Values.ToList()
            };

            if (content.Streams.Count > 0)
                output.Write(content.Serialize());
        }
```

I will see if I can put a PR up with that sometime this week.

**Comment by JosephWoodward** [comment]
@steveadoo32 I'd love to see a PR around this, especially this part:

> After making those two changes, my loki chunks went from over a million from a week of runtime down to about ~4k.

**Comment by JosephWoodward** [comment]
The [latest 3.0.0 release](https://www.nuget.org/packages/Serilog.Sinks.Loki/3.0.0) now a [PropertiesAsLabels](https://github.com/JosephWoodward/Serilog-Sinks-Loki/blob/d88dde06c9195ed13e4b25060950f73213b1ba5d/src/Serilog.Sinks.Loki/Labels/DefaultLogLabelProvider.cs#L12) field that allows you to configure which properties should be treated as labels.

I'll close this issue off, if there are any further issues then please feel free to re-open it.
