### ISSUE TITLE
Version 2.1.0 is not published on nuget

### ISSUE THREAD

**Issue by cagianx** [JosephWoodward/Serilog-Sinks-Loki#16]
I notice that on nuget.org the [release v2.10](https://github.com/JosephWoodward/Serilog-Sinks-Loki/releases/tag/v2.1.0) is missing: https://www.nuget.org/packages/Serilog.Sinks.Loki/

Will the package be published on nuget.org? 

Thank you

**Comment by JosephWoodward** [comment]
@cagianx Oh goodness, thank you for reminding me! This has now been published and [is available on NuGet here](https://www.nuget.org/packages/Serilog.Sinks.Loki/2.1.0).

**Comment by JosephWoodward** [comment]
I'll close this issue, feel free to re-open it if you have any issues.

Thanks!
