### ISSUE TITLE
LogEntry timestamp

### ISSUE THREAD

**Issue by Kromi75** [JosephWoodward/Serilog-Sinks-Loki#17]
Hi Joseph,

When I run the included test program and check the logs with Grafana, I find that many log entries have exactly the same timestamp - down to the millisecond.

So my question: Why don't you use LogEvent.Timestamp instead of DateTime.Now?

Regards,
Mathias

**Comment by JosephWoodward** [comment]
> Hi Joseph,
> 
> When I run the included test program and check the logs with Grafana, I find that many log entries have exactly the same timestamp - down to the millisecond.
> 
> So my question: Why don't you use LogEvent.Timestamp instead of DateTime.Now?
> 
> Regards,
> Mathias

That's a very good idea, I'd be happy to accept a PR for this?

**Comment by Kromi75** [comment]
Sure: [#18](https://github.com/JosephWoodward/Serilog-Sinks-Loki/pull/18)
