### ISSUE TITLE
Logs are been sent as a batch once in 10 minutes

### ISSUE THREAD

**Issue by isabr85** [JosephWoodward/Serilog-Sinks-Loki#26]
I couldn't find the way to set the time interval definition.
In grafana I can see the logs arriving each 10 minutes. Their 'parsed timestamp' is almost identical because of that,
is there any way to set to the time interval value?

**Comment by JosephWoodward** [comment]
@isabr85 The Loki SeriLog sink sits on top of the [Http Sink](https://github.com/FantasticFiasco/serilog-sinks-http) so you'll need to configure how often logs are shipped in there.

**Comment by augustoproiete** [comment]
@JosephWoodward I briefly looked at [`LokiSinkExtensions`](https://github.com/JosephWoodward/Serilog-Sinks-Loki/blob/master/src/Serilog.Sinks.Loki/LokiSinkExtensions.cs) and it doesn't seem like you're exposing any way of configuring the [settings that the Http Sink supports](https://github.com/FantasticFiasco/serilog-sinks-http/blob/master/src/Serilog.Sinks.Http/LoggerSinkConfigurationExtensions.cs) such as `batchPostingLimit`, `period`, etc.

**Comment by Nefarion** [comment]
Default HttpSink period is 2 seconds, it gets bigger if more than the last request has failed.

**Comment by chatwithdipesh** [comment]
First of all thank you for this @JosephWoodward. However even we are running into exact same problem raised by @augustoproiete, where in initially I could see the logs in Grafana Loki almost real time (for initial couple of minutes) but after that it is taking ~10mins to  get updated with later timestamp. Also I checked the code and given LokiHttp implements IHttpClient (and not derive from HttpSink/PeriodicBatchingSink) I am not sure how we can configure batchPostingLimit/period using  LoggerSinkConfigurationExtensions

**Comment by REscobar** [comment]
> First of all thank you for this @JosephWoodward. However even we are running into exact same problem raised by @augustoproiete, where in initially I could see the logs in Grafana Loki almost real time (for initial couple of minutes) but after that it is taking ~10mins to get updated with later timestamp. Also couldn't find any option to configure batchPostingLimit, period, etc.

Use https://github.com/adeotek/Serilog.Sinks.GrafanaLoki
https://www.nuget.org/packages/Serilog.Sinks.GrafanaLoki/
