### ISSUE TITLE
The assembly inside the latest package (https://www.nuget.org/packages/Serilog.Sinks.Loki/2.2.0)  does not contain the line ending and back-to-forward slashes fixes by #13

### ISSUE THREAD

**Issue by REscobar** [JosephWoodward/Serilog-Sinks-Loki#27]
The assembly inside the latest package (https://www.nuget.org/packages/Serilog.Sinks.Loki/2.2.0)  does not contain the line ending and back-to-forward slashes fixes by #13 

![image](https://user-images.githubusercontent.com/348416/96536394-307bc200-1251-11eb-8fa0-758b3db533a6.png)

![image](https://user-images.githubusercontent.com/348416/96536444-543f0800-1251-11eb-91d9-c7de0d2523b2.png)

_Originally posted by @REscobar in https://github.com/JosephWoodward/Serilog-Sinks-Loki/issues/21#issuecomment-712563792_

**Comment by kaflake** [comment]
It also not contains #18 if I pull the assembly over nuget. But if I use the source it is working.
There seem to be an wrong assembly.

**Comment by kaflake** [comment]
Comparing the assembly in the NuGet you can see, that they are in Version 2.1 and 2.2 identical.

**Comment by JosephWoodward** [comment]
@kaflake @REscobar Yes, I must have missed this. I'm publishing an update that includes these now.

**Comment by JosephWoodward** [comment]
@kaflake @REscobar This is available as part of the latest [3.0.0](https://www.nuget.org/packages/Serilog.Sinks.Loki/) release.

**Comment by jincod** [comment]
Hi @JosephWoodward,

![image](https://user-images.githubusercontent.com/1294432/98818709-bc969900-244d-11eb-9319-9842e0634c12.png)


The same issue for 3.0.0. Nuget contains 2.1.0 build. Could you please check it?
