### ISSUE TITLE
Ooops in Console Output

### ISSUE THREAD

**Issue by MarcelMalik** [JosephWoodward/Serilog-Sinks-Loki#4]
With each error, an "Ooops" from LokiBatchFormatter is written to the console.
Why?
Can you please remove this behaviour?

**Comment by JosephWoodward** [comment]
Yes! It looks like I'd [missed that when cleaning it up](https://github.com/JosephWoodward/Serilog-Sinks-Loki/blob/c22e9e01e89253199a34190d8e808a0f16e84b10/src/Serilog.Sinks.Loki/LokiBatchFormatter.cs#L54) ready for release.

**Comment by JosephWoodward** [comment]
Sorry I haven't gotten around to doing this yet!

**Comment by JosephWoodward** [comment]
This has been fixed in https://www.nuget.org/packages/Serilog.Sinks.Loki/1.0.1
