### ISSUE TITLE
v4.0.0-beta1 not using new build

### ISSUE THREAD

**Issue by Falco20019** [JosephWoodward/Serilog-Sinks-Loki#50]
Hi @JosephWoodward,

I just tried the new NuGet package, but sadly it still contains the DLLs for `3.0.1-beta1+27e063c30c3411b74b2f33788dcd4116e14db3f1`. So there definitely went something wrong while releasing. It also does not contain any of the changes. Can you please re-release (or try the build chain from @michaelosthege)?

**Comment by Falco20019** [comment]
@JosephWoodward The package is still broken.

**Comment by JosephWoodward** [comment]
I'll release a new version today.

**Comment by Falco20019** [comment]
Thanks. Would be great if we could also get #51 in, it's a minor fix but makes usage easier :)

**Comment by JosephWoodward** [comment]
@Falco20019 Sorry, just seen your follow up message. Try that one? https://www.nuget.org/packages/Serilog.Sinks.Loki/4.0.0-beta2

If that's working then I'll merge #51 and publish a beta3.

**Comment by Falco20019** [comment]
Yep, that version contains the correct DLL :) Thanks. Looking forward to `beta3`!
