### ISSUE TITLE
Feature request: Support for using Serilog Settings Configuration

### ISSUE THREAD

**Issue by vasicvuk** [JosephWoodward/Serilog-Sinks-Loki#6]
Idea is to support configuration of Loki sync over Serilog Settings Configuration https://github.com/serilog/serilog-settings-configuration.

If this is already available then only documentation is needed.

I guess that Sink constructor has to be change to use primitive types for configuration of Url, User and Pass

**Comment by JosephWoodward** [comment]
Good idea! If you'd like to contribute this then it'd certainly be appreciated, otherwise I can look at picking it up shortly.
